Wire Filters UI
bigbinary/neeto-filters-frontend pull request #14
Opened 2022-04-05 06:53 UTC by AbhayVAshokan

Fixes #13
- Added submit button and modal.
- Used `context` for state management.
- Inputs can be submitted using `Enter` keybinding.
- Added an ErrorBoundary to prevent `neetoFilters` from crashing the entire application during breaking changes.

2022-04-05 06:56 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-04-05 12:38 UTC, Amaljith-K requested changes
@AbhayVAshokan _a

2022-04-06 05:39 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-04-06 10:33 UTC, Amaljith-K reviewed
@AbhayVAshokan _a

2022-04-06 10:33 UTC, Amaljith-K commented on src/components/Submit/Confirmation.jsx
> +    return true;
Why is this line required?

2022-04-06 10:49 UTC, AbhayVAshokan commented
@Amaljith-K _a please have a look.

2022-04-08 08:29 UTC, Amaljith-K approved these changes
@AbhayVAshokan _a everything else looks good to me.
Please merge yourself after making the suggested change

2022-04-08 08:29 UTC, Amaljith-K commented on src/components/Main.jsx
> +  const handleChangeRef = useRef(onChange);
Why do we need `handleChangeRef`?

2022-04-08 10:20 UTC, AbhayVAshokan commented on src/components/Main.jsx
> +  const handleChangeRef = useRef(onChange);
@Amaljith-K the `useEffect` on line 29 depends on both `segment` and `onChange`. I wasn't so sure if adding `onChange` in the dependency array (as shown below) to respect the rules of hooks was a good approach. The `onChange` method should be called only when there is a change in the value of `segment`.  It will be calling an API behind the scenes. Using refs is one way to satisfy the rules of hooks.
```jsx
  useEffect(() => {
    onChange(segment);
  }, [onChange, segment]);
```

2022-04-08 10:47 UTC, Amaljith-K commented on src/components/Main.jsx
> +  const handleChangeRef = useRef(onChange);
You don't need ref.
Ideally, to fix the lint, you were supposed to wrap the function inside a useCallback hook.
But since that introduces additional complexity, we don't usually do that unless there is some specific need.

Even though ES-Lint shows a warning, it is kind of a false positive. This should work perfectly well for your requirement:
```js
  useEffect(() => {
    onChange(segment);
  }, [segment]);
```

2022-04-08 11:17 UTC, merged