Added ability to delete filters and segments, validations for filters
bigbinary/neeto-filters-frontend pull request #18
Opened 2022-04-12 10:28 UTC by AbhayVAshokan

Fixes #16
- Added the functionality to delete segments.
- Added the functionality to delete individual filter blocks.
- Added datatype validations for dropdown items.
- Updated neetoUI to v3.3.6.
- Updated neetoIcons to v1.8.30.
- Fixed minor bugs in FilterDropdown component.

Demo: https://vimeo.com/698550820/56022b2939

2022-04-12 10:33 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-04-13 03:58 UTC, Amaljith-K requested changes
@AbhayVAshokan _a

2022-04-13 03:58 UTC, Amaljith-K commented on src/components/Delete.jsx
> +  const isUpdate = !isNil(segment.id);
```suggestion
  const isUpdate = !segment.id;
```

2022-04-13 03:58 UTC, Amaljith-K commented on src/components/FilterBlock.jsx
> +  const [, dispatchSegment] = useSegment();
```suggestion
  const dispatchSegment = useSegment()[1];
```

2022-04-13 03:58 UTC, Amaljith-K commented on src/components/FilterDropdown/index.jsx
> +    }
This is safer from race conditions
```suggestion
    setIsFilterDropdownOpen(isOpen => {
      if (isOpen) setSelectedNode(node);
      return !isOpen;
    });
```

2022-04-13 03:58 UTC, Amaljith-K commented on src/components/FilterDropdown/utils.js
> +};
https://vimeo.com/698874116/f1a11de972

2022-04-13 04:39 UTC, AbhayVAshokan commented
@Amaljith-K _a please have a look: https://vimeo.com/698882285/abe7d70cc7

2022-04-14 07:23 UTC, Amaljith-K approved these changes
LGTM except for one minor comment.
Please make the changes and merge

2022-04-14 07:23 UTC, Amaljith-K commented on example/src/App.jsx
> +  };
```suggestion
  const handleDelete = () => new Promise(resolve => setTimeout(resolve, 1000));
```
There is no need for additional async await wrap when you are already returning a promise.

2022-04-14 10:23 UTC, merged