Create Filter UI
bigbinary/neeto-filters-frontend pull request #8
Opened 2022-03-25 12:03 UTC by AbhayVAshokan

Fixes #7 
- Added UI for `neetoFilters` package.
- Wiring will be taken up as a separate issue. Currently, the functionality is minimal with sample data from `constants.js` file.

2022-03-25 12:06 UTC, AbhayVAshokan commented
@karthiknmenon _a can you please verify the UI? Once, done we'll assign @Amaljith-K for a detailed code review.

2022-03-25 12:16 UTC, karthiknmenon commented
@AbhayVAshokan _a Could you please add screenshots to the PR description?

2022-03-25 12:17 UTC, AbhayVAshokan commented
@karthiknmenon I've requested for deploying neetoFilters example app to Netlify. Will assign you back once done.

2022-03-25 12:53 UTC, AbhayVAshokan commented
@karthiknmenon _a please review.
Link: https://deploy-preview-8--neeto-filters.netlify.app/

2022-03-25 16:31 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-03-28 10:36 UTC, Amaljith-K requested changes
@AbhayVAshokan _a

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterBlock.jsx
> +          {`${humanize(rule, false)} ${value}`}
```suggestion
          {humanize(rule, false)} {value}
```

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterDropdown/ColumnSelector.jsx
> +              <li key={index} onClick={() => setNode("node")}>
Use `node` as key.
Using `index` as key might sometimes introduce unexpected behaviors.
Apply this suggestion wherever possible throughout this PR. Example: src/components/FilterDropdown/LogicSelector.jsx

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterDropdown/LogicSelector.jsx
> +    <>
Prefer implicit returns
```suggestion
const LogicSelector = ({ node, setNode }) => (
  <>
```

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterDropdown/LogicSelector.jsx
> +                ) : (
Don't we support date picker with time?

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterDropdown/LogicSelector.jsx
> +                  index === 0 && <Input autoFocus />
Is rendering `false` for all indices except `0` intentional? If yes, please explain to me the reason why we aren't rendering input fields for other indices

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterGroup.jsx
> +    (index) => and(!isEmpty(conditions), index !== conditions.length - 1),
Infix form is easier to comprehend.
```suggestion
    (index) => !isEmpty(conditions) && index !== conditions.length - 1,
```

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterGroup.jsx
> +            key={index}
Since this is not a direct element of an array, you don't need key here.

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/JoinSelector.jsx
> +  return (
Prefer implicit return all over this PR.

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/index.jsx
> +      and(!isEmpty(SAMPLE_FILTERS), index !== SAMPLE_FILTERS.length - 1),
Since `SAMPLE_FILTERS` is a hardcoded value, it is guaranteed to be always non-empty.
What is the use of the first part of this condition?

2022-03-28 10:36 UTC, Amaljith-K commented on src/components/FilterDropdown/LogicSelector.jsx
> +                {type === "date" ? (
As per the current code, these are the mistakes here:
- Elements of `LOGIC_LABELS` don't have an attribute `type` in them. It only has `label` and `checked`.
- type = `date` is not defined in `ATTRIBUTE_TYPES` either. It only contains `time`.

2022-03-28 10:36 UTC, Amaljith-K requested changes
@AbhayVAshokan _a

2022-03-28 10:58 UTC, AbhayVAshokan commented on src/components/index.jsx
> +      and(!isEmpty(SAMPLE_FILTERS), index !== SAMPLE_FILTERS.length - 1),
Yes, `SAMPLE_FILTERS` is a hard-coded value. During wiring, the `SAMPLE_FILTERS` constant will get replaced by the content in the `segment` prop, thus making the condition useful.

2022-03-28 12:35 UTC, Amaljith-K commented
@AbhayVAshokan _a
Also, can we do this? https://vimeo.com/693082352/55e8eb60a4

2022-03-29 07:15 UTC, Amaljith-K commented on src/components/index.jsx
> +      and(!isEmpty(SAMPLE_FILTERS), index !== SAMPLE_FILTERS.length - 1),
https://vimeo.com/693420741/ccbf26d446

2022-03-29 07:23 UTC, Amaljith-K commented
@AbhayVAshokan Another UI suggestion: https://vimeo.com/693422978/67677a1e35

2022-03-29 07:24 UTC, Amaljith-K commented on src/components/FilterDropdown/LogicSelector.jsx
> +    (node) => node === selectedLogic
Create a new issue to import all ESLint and prettier configurations from the wheel repo and apply it to all files.

2022-03-29 07:24 UTC, Amaljith-K commented on src/components/index.jsx
> +      and(!isEmpty(SAMPLE_FILTERS), index !== SAMPLE_FILTERS.length - 1),
In the same way, avoid all sample data constants from all files in the core component.
Accept all those values from props.
This will make the wiring easier.

2022-03-29 07:31 UTC, Amaljith-K commented
A bug in the implementation: https://vimeo.com/693425174/02e781302d

2022-03-29 07:33 UTC, Amaljith-K reviewed
@AbhayVAshokan _a
please check these comments too

2022-03-29 07:33 UTC, Amaljith-K commented on src/utils.js
> +export const humanize = (string, capitalize = true) => {
Can you contribute this function to [neeto-utils](https://github.com/bigbinary/neeto-utils) repo?

2022-03-29 13:49 UTC, AbhayVAshokan commented
@Amaljith-K _a please have a look.

2022-03-30 12:50 UTC, Amaljith-K approved these changes
LGTM

2022-03-30 12:50 UTC, merged